// flow-typed signature: 6ddcb9c27022d8cc81f7bb3522e83ef0
// flow-typed version: <<STUB>>/reflect-metadata_v0.1.9/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reflect-metadata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reflect-metadata' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reflect-metadata/Reflect' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/Reflect' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/harness' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/reflect/reflect-decorate' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/reflect/reflect-definemetadata' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/reflect/reflect-deletemetadata' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/reflect/reflect-getmetadata' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/reflect/reflect-getmetadatakeys' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/reflect/reflect-getownmetadata' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/reflect/reflect-getownmetadatakeys' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/reflect/reflect-hasmetadata' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/reflect/reflect-hasownmetadata' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/reflect/reflect-metadata' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/run' {
  declare module.exports: any;
}

declare module 'reflect-metadata/temp/test/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reflect-metadata/Reflect.js' {
  declare module.exports: $Exports<'reflect-metadata/Reflect'>;
}
declare module 'reflect-metadata/temp/Reflect.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/Reflect'>;
}
declare module 'reflect-metadata/temp/test/harness.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/harness'>;
}
declare module 'reflect-metadata/temp/test/reflect/reflect-decorate.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/reflect/reflect-decorate'>;
}
declare module 'reflect-metadata/temp/test/reflect/reflect-definemetadata.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/reflect/reflect-definemetadata'>;
}
declare module 'reflect-metadata/temp/test/reflect/reflect-deletemetadata.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/reflect/reflect-deletemetadata'>;
}
declare module 'reflect-metadata/temp/test/reflect/reflect-getmetadata.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/reflect/reflect-getmetadata'>;
}
declare module 'reflect-metadata/temp/test/reflect/reflect-getmetadatakeys.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/reflect/reflect-getmetadatakeys'>;
}
declare module 'reflect-metadata/temp/test/reflect/reflect-getownmetadata.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/reflect/reflect-getownmetadata'>;
}
declare module 'reflect-metadata/temp/test/reflect/reflect-getownmetadatakeys.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/reflect/reflect-getownmetadatakeys'>;
}
declare module 'reflect-metadata/temp/test/reflect/reflect-hasmetadata.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/reflect/reflect-hasmetadata'>;
}
declare module 'reflect-metadata/temp/test/reflect/reflect-hasownmetadata.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/reflect/reflect-hasownmetadata'>;
}
declare module 'reflect-metadata/temp/test/reflect/reflect-metadata.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/reflect/reflect-metadata'>;
}
declare module 'reflect-metadata/temp/test/run.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/run'>;
}
declare module 'reflect-metadata/temp/test/spec.js' {
  declare module.exports: $Exports<'reflect-metadata/temp/test/spec'>;
}
