// flow-typed signature: 45cd5886c11499c5d2fc25aaa534b5ab
// flow-typed version: <<STUB>>/typeorm_v0.0.6/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeorm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeorm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typeorm/cli' {
  declare module.exports: any;
}

declare module 'typeorm/commands/EntityCreateCommand' {
  declare module.exports: any;
}

declare module 'typeorm/commands/MigrationCreateCommand' {
  declare module.exports: any;
}

declare module 'typeorm/commands/MigrationRevertCommand' {
  declare module.exports: any;
}

declare module 'typeorm/commands/MigrationRunCommand' {
  declare module.exports: any;
}

declare module 'typeorm/commands/QueryCommand' {
  declare module.exports: any;
}

declare module 'typeorm/commands/SchemaDropCommand' {
  declare module.exports: any;
}

declare module 'typeorm/commands/SchemaSyncCommand' {
  declare module.exports: any;
}

declare module 'typeorm/commands/SubscriberCreateCommand' {
  declare module.exports: any;
}

declare module 'typeorm/common/ObjectLiteral' {
  declare module.exports: any;
}

declare module 'typeorm/common/ObjectType' {
  declare module.exports: any;
}

declare module 'typeorm/connection/Connection' {
  declare module.exports: any;
}

declare module 'typeorm/connection/ConnectionManager' {
  declare module.exports: any;
}

declare module 'typeorm/connection/ConnectionOptions' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/AlreadyHasActiveConnectionError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/CannotCloseNotConnectedError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/CannotConnectAlreadyConnectedError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/CannotDetermineConnectionOptionsError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/CannotGetEntityManagerNotConnectedError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/CannotImportAlreadyConnectedError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/CannotRunMigrationNotConnectedError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/CannotSyncNotConnectedError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/CannotUseNamingStrategyNotConnectedError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/ConnectionNotFoundError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/MissingDriverError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/NamingStrategyNotFoundError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/NoConnectionForRepositoryError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/RepositoryNotFoundError' {
  declare module.exports: any;
}

declare module 'typeorm/connection/error/RepositoryNotTreeError' {
  declare module.exports: any;
}

declare module 'typeorm/container' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/columns/Column' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/columns/CreateDateColumn' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/columns/DiscriminatorColumn' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/columns/PrimaryColumn' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/columns/PrimaryGeneratedColumn' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/columns/UpdateDateColumn' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/columns/VersionColumn' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/DiscriminatorValue' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/Embedded' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/error/ColumnTypeUndefinedError' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/error/GeneratedOnlyForPrimaryError' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/error/PrimaryColumnCannotBeNullableError' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/Index' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/listeners/AfterInsert' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/listeners/AfterLoad' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/listeners/AfterRemove' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/listeners/AfterUpdate' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/listeners/BeforeInsert' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/listeners/BeforeRemove' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/listeners/BeforeUpdate' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/listeners/EventSubscriber' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/NamingStrategy' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/options/ColumnOptions' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/options/IndexOptions' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/options/JoinColumnOptions' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/options/JoinTableOptions' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/options/RelationOptions' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/options/TableOptions' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/relations/JoinColumn' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/relations/JoinTable' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/relations/ManyToMany' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/relations/ManyToOne' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/relations/OneToMany' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/relations/OneToOne' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/relations/RelationCount' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/relations/RelationId' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/tables/AbstractTable' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/tables/ClassTableChild' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/tables/ClosureTable' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/tables/EmbeddableTable' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/tables/SingleTableChild' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/tables/Table' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/tables/TableInheritance' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/tree/TreeChildren' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/tree/TreeLevelColumn' {
  declare module.exports: any;
}

declare module 'typeorm/decorator/tree/TreeParent' {
  declare module.exports: any;
}

declare module 'typeorm/decorators-shim' {
  declare module.exports: any;
}

declare module 'typeorm/driver/DatabaseConnection' {
  declare module.exports: any;
}

declare module 'typeorm/driver/Driver' {
  declare module.exports: any;
}

declare module 'typeorm/driver/DriverOptions' {
  declare module.exports: any;
}

declare module 'typeorm/driver/DriverUtils' {
  declare module.exports: any;
}

declare module 'typeorm/driver/error/ConnectionIsNotSetError' {
  declare module.exports: any;
}

declare module 'typeorm/driver/error/DataTypeNotSupportedByDriverError' {
  declare module.exports: any;
}

declare module 'typeorm/driver/error/DriverOptionNotSetError' {
  declare module.exports: any;
}

declare module 'typeorm/driver/error/DriverPackageLoadError' {
  declare module.exports: any;
}

declare module 'typeorm/driver/error/DriverPackageNotInstalledError' {
  declare module.exports: any;
}

declare module 'typeorm/driver/error/DriverPoolingNotSupportedError' {
  declare module.exports: any;
}

declare module 'typeorm/driver/error/TransactionAlreadyStartedError' {
  declare module.exports: any;
}

declare module 'typeorm/driver/error/TransactionNotStartedError' {
  declare module.exports: any;
}

declare module 'typeorm/driver/mysql/MysqlDriver' {
  declare module.exports: any;
}

declare module 'typeorm/driver/mysql/MysqlQueryRunner' {
  declare module.exports: any;
}

declare module 'typeorm/driver/oracle/OracleDriver' {
  declare module.exports: any;
}

declare module 'typeorm/driver/oracle/OracleQueryRunner' {
  declare module.exports: any;
}

declare module 'typeorm/driver/postgres/PostgresDriver' {
  declare module.exports: any;
}

declare module 'typeorm/driver/postgres/PostgresQueryRunner' {
  declare module.exports: any;
}

declare module 'typeorm/driver/sqlite/SqliteDriver' {
  declare module.exports: any;
}

declare module 'typeorm/driver/sqlite/SqliteQueryRunner' {
  declare module.exports: any;
}

declare module 'typeorm/driver/sqlserver/SqlServerDriver' {
  declare module.exports: any;
}

declare module 'typeorm/driver/sqlserver/SqlServerQueryRunner' {
  declare module.exports: any;
}

declare module 'typeorm/driver/websql/WebsqlDriver' {
  declare module.exports: any;
}

declare module 'typeorm/driver/websql/WebsqlQueryRunner' {
  declare module.exports: any;
}

declare module 'typeorm/entity-manager/BaseEntityManager' {
  declare module.exports: any;
}

declare module 'typeorm/entity-manager/EntityManager' {
  declare module.exports: any;
}

declare module 'typeorm/entity-manager/error/NoNeedToReleaseEntityManagerError' {
  declare module.exports: any;
}

declare module 'typeorm/entity-schema/EntitySchema' {
  declare module.exports: any;
}

declare module 'typeorm/find-options/FindOptions' {
  declare module.exports: any;
}

declare module 'typeorm/find-options/FindOptionsUtils' {
  declare module.exports: any;
}

declare module 'typeorm/find-options/OrderByCondition' {
  declare module.exports: any;
}

declare module 'typeorm/lazy-loading/LazyRelationsWrapper' {
  declare module.exports: any;
}

declare module 'typeorm/logger/Logger' {
  declare module.exports: any;
}

declare module 'typeorm/logger/LoggerOptions' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/collection/PropertyMetadataArgsCollection' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/collection/TargetMetadataArgsCollection' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/ColumnMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/DiscriminatorValueMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/EmbeddedMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/EntityListenerMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/EntityMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/EntitySubscriberMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/error/EntityMetadataNotFound' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/IndexMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/InheritanceMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/JoinColumnMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/JoinTableMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/MetadataArgsStorage' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/NamingStrategyMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/RelationCountMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/RelationIdMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/RelationMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-args/TableMetadataArgs' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/ClosureJunctionEntityMetadataBuilder' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/EntityMetadataBuilder' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/EntityMetadataValidator' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/error/CircularRelationsError' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/error/MetadataAlreadyExistsError' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/error/MetadataWithSuchNameAlreadyExistsError' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/error/MissingJoinColumnError' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/error/MissingJoinTableError' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/error/MissingPrimaryColumnError' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/error/UsingJoinColumnIsNotAllowedError' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/error/UsingJoinColumnOnlyOnOneSideAllowedError' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/error/UsingJoinTableIsNotAllowedError' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/error/UsingJoinTableOnlyOnOneSideAllowedError' {
  declare module.exports: any;
}

declare module 'typeorm/metadata-builder/JunctionEntityMetadataBuilder' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/ColumnMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/EmbeddedMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/EntityListenerMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/EntityMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/EntitySubscriberMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/error/EntityMetadataAlreadySetError' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/error/EntityMetadataNotSetError' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/ForeignKeyMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/IndexMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/JoinColumnMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/JoinTableMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/PropertyMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/RelationCountMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/RelationMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/TableMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/TargetMetadata' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/types/ColumnTypes' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/types/EventListenerTypes' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/types/RelationTypes' {
  declare module.exports: any;
}

declare module 'typeorm/metadata/types/TableTypes' {
  declare module.exports: any;
}

declare module 'typeorm/migration/Migration' {
  declare module.exports: any;
}

declare module 'typeorm/migration/MigrationExecutor' {
  declare module.exports: any;
}

declare module 'typeorm/migration/MigrationInterface' {
  declare module.exports: any;
}

declare module 'typeorm/naming-strategy/DefaultNamingStrategy' {
  declare module.exports: any;
}

declare module 'typeorm/naming-strategy/NamingStrategyInterface' {
  declare module.exports: any;
}

declare module 'typeorm/persistence/error/CascadesNotAllowedError' {
  declare module.exports: any;
}

declare module 'typeorm/persistence/error/PersistedEntityNotFoundError' {
  declare module.exports: any;
}

declare module 'typeorm/persistence/Subject' {
  declare module.exports: any;
}

declare module 'typeorm/persistence/SubjectBuilder' {
  declare module.exports: any;
}

declare module 'typeorm/persistence/SubjectOperationExecutor' {
  declare module.exports: any;
}

declare module 'typeorm/platform/PlatformTools' {
  declare module.exports: any;
}

declare module 'typeorm/query-builder/alias/Alias' {
  declare module.exports: any;
}

declare module 'typeorm/query-builder/alias/AliasMap' {
  declare module.exports: any;
}

declare module 'typeorm/query-builder/JoinOptions' {
  declare module.exports: any;
}

declare module 'typeorm/query-builder/QueryBuilder' {
  declare module.exports: any;
}

declare module 'typeorm/query-builder/transformer/PlainObjectToDatabaseEntityTransformer' {
  declare module.exports: any;
}

declare module 'typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer' {
  declare module.exports: any;
}

declare module 'typeorm/query-builder/transformer/RawSqlResultsToEntityTransformer' {
  declare module.exports: any;
}

declare module 'typeorm/query-runner/error/QueryRunnerAlreadyReleasedError' {
  declare module.exports: any;
}

declare module 'typeorm/query-runner/error/QueryRunnerProviderAlreadyReleasedError' {
  declare module.exports: any;
}

declare module 'typeorm/query-runner/QueryRunner' {
  declare module.exports: any;
}

declare module 'typeorm/query-runner/QueryRunnerProvider' {
  declare module.exports: any;
}

declare module 'typeorm/repository/Repository' {
  declare module.exports: any;
}

declare module 'typeorm/repository/RepositoryAggregator' {
  declare module.exports: any;
}

declare module 'typeorm/repository/RepositoryFactory' {
  declare module.exports: any;
}

declare module 'typeorm/repository/SpecificRepository' {
  declare module.exports: any;
}

declare module 'typeorm/repository/TreeRepository' {
  declare module.exports: any;
}

declare module 'typeorm/schema-builder/schema/ColumnSchema' {
  declare module.exports: any;
}

declare module 'typeorm/schema-builder/schema/ForeignKeySchema' {
  declare module.exports: any;
}

declare module 'typeorm/schema-builder/schema/IndexSchema' {
  declare module.exports: any;
}

declare module 'typeorm/schema-builder/schema/PrimaryKeySchema' {
  declare module.exports: any;
}

declare module 'typeorm/schema-builder/schema/TableSchema' {
  declare module.exports: any;
}

declare module 'typeorm/schema-builder/SchemaBuilder' {
  declare module.exports: any;
}

declare module 'typeorm/subscriber/Broadcaster' {
  declare module.exports: any;
}

declare module 'typeorm/subscriber/EntitySubscriberInterface' {
  declare module.exports: any;
}

declare module 'typeorm/subscriber/event/InsertEvent' {
  declare module.exports: any;
}

declare module 'typeorm/subscriber/event/RemoveEvent' {
  declare module.exports: any;
}

declare module 'typeorm/subscriber/event/UpdateEvent' {
  declare module.exports: any;
}

declare module 'typeorm/util/DataTransformationUtils' {
  declare module.exports: any;
}

declare module 'typeorm/util/DepGraph' {
  declare module.exports: any;
}

declare module 'typeorm/util/DirectoryExportedClassesLoader' {
  declare module.exports: any;
}

declare module 'typeorm/util/OrmUtils' {
  declare module.exports: any;
}

declare module 'typeorm/util/PromiseUtils' {
  declare module.exports: any;
}

declare module 'typeorm/util/RandomGenerator' {
  declare module.exports: any;
}

declare module 'typeorm/util/StringUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typeorm/cli.js' {
  declare module.exports: $Exports<'typeorm/cli'>;
}
declare module 'typeorm/commands/EntityCreateCommand.js' {
  declare module.exports: $Exports<'typeorm/commands/EntityCreateCommand'>;
}
declare module 'typeorm/commands/MigrationCreateCommand.js' {
  declare module.exports: $Exports<'typeorm/commands/MigrationCreateCommand'>;
}
declare module 'typeorm/commands/MigrationRevertCommand.js' {
  declare module.exports: $Exports<'typeorm/commands/MigrationRevertCommand'>;
}
declare module 'typeorm/commands/MigrationRunCommand.js' {
  declare module.exports: $Exports<'typeorm/commands/MigrationRunCommand'>;
}
declare module 'typeorm/commands/QueryCommand.js' {
  declare module.exports: $Exports<'typeorm/commands/QueryCommand'>;
}
declare module 'typeorm/commands/SchemaDropCommand.js' {
  declare module.exports: $Exports<'typeorm/commands/SchemaDropCommand'>;
}
declare module 'typeorm/commands/SchemaSyncCommand.js' {
  declare module.exports: $Exports<'typeorm/commands/SchemaSyncCommand'>;
}
declare module 'typeorm/commands/SubscriberCreateCommand.js' {
  declare module.exports: $Exports<'typeorm/commands/SubscriberCreateCommand'>;
}
declare module 'typeorm/common/ObjectLiteral.js' {
  declare module.exports: $Exports<'typeorm/common/ObjectLiteral'>;
}
declare module 'typeorm/common/ObjectType.js' {
  declare module.exports: $Exports<'typeorm/common/ObjectType'>;
}
declare module 'typeorm/connection/Connection.js' {
  declare module.exports: $Exports<'typeorm/connection/Connection'>;
}
declare module 'typeorm/connection/ConnectionManager.js' {
  declare module.exports: $Exports<'typeorm/connection/ConnectionManager'>;
}
declare module 'typeorm/connection/ConnectionOptions.js' {
  declare module.exports: $Exports<'typeorm/connection/ConnectionOptions'>;
}
declare module 'typeorm/connection/error/AlreadyHasActiveConnectionError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/AlreadyHasActiveConnectionError'>;
}
declare module 'typeorm/connection/error/CannotCloseNotConnectedError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/CannotCloseNotConnectedError'>;
}
declare module 'typeorm/connection/error/CannotConnectAlreadyConnectedError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/CannotConnectAlreadyConnectedError'>;
}
declare module 'typeorm/connection/error/CannotDetermineConnectionOptionsError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/CannotDetermineConnectionOptionsError'>;
}
declare module 'typeorm/connection/error/CannotGetEntityManagerNotConnectedError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/CannotGetEntityManagerNotConnectedError'>;
}
declare module 'typeorm/connection/error/CannotImportAlreadyConnectedError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/CannotImportAlreadyConnectedError'>;
}
declare module 'typeorm/connection/error/CannotRunMigrationNotConnectedError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/CannotRunMigrationNotConnectedError'>;
}
declare module 'typeorm/connection/error/CannotSyncNotConnectedError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/CannotSyncNotConnectedError'>;
}
declare module 'typeorm/connection/error/CannotUseNamingStrategyNotConnectedError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/CannotUseNamingStrategyNotConnectedError'>;
}
declare module 'typeorm/connection/error/ConnectionNotFoundError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/ConnectionNotFoundError'>;
}
declare module 'typeorm/connection/error/MissingDriverError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/MissingDriverError'>;
}
declare module 'typeorm/connection/error/NamingStrategyNotFoundError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/NamingStrategyNotFoundError'>;
}
declare module 'typeorm/connection/error/NoConnectionForRepositoryError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/NoConnectionForRepositoryError'>;
}
declare module 'typeorm/connection/error/RepositoryNotFoundError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/RepositoryNotFoundError'>;
}
declare module 'typeorm/connection/error/RepositoryNotTreeError.js' {
  declare module.exports: $Exports<'typeorm/connection/error/RepositoryNotTreeError'>;
}
declare module 'typeorm/container.js' {
  declare module.exports: $Exports<'typeorm/container'>;
}
declare module 'typeorm/decorator/columns/Column.js' {
  declare module.exports: $Exports<'typeorm/decorator/columns/Column'>;
}
declare module 'typeorm/decorator/columns/CreateDateColumn.js' {
  declare module.exports: $Exports<'typeorm/decorator/columns/CreateDateColumn'>;
}
declare module 'typeorm/decorator/columns/DiscriminatorColumn.js' {
  declare module.exports: $Exports<'typeorm/decorator/columns/DiscriminatorColumn'>;
}
declare module 'typeorm/decorator/columns/PrimaryColumn.js' {
  declare module.exports: $Exports<'typeorm/decorator/columns/PrimaryColumn'>;
}
declare module 'typeorm/decorator/columns/PrimaryGeneratedColumn.js' {
  declare module.exports: $Exports<'typeorm/decorator/columns/PrimaryGeneratedColumn'>;
}
declare module 'typeorm/decorator/columns/UpdateDateColumn.js' {
  declare module.exports: $Exports<'typeorm/decorator/columns/UpdateDateColumn'>;
}
declare module 'typeorm/decorator/columns/VersionColumn.js' {
  declare module.exports: $Exports<'typeorm/decorator/columns/VersionColumn'>;
}
declare module 'typeorm/decorator/DiscriminatorValue.js' {
  declare module.exports: $Exports<'typeorm/decorator/DiscriminatorValue'>;
}
declare module 'typeorm/decorator/Embedded.js' {
  declare module.exports: $Exports<'typeorm/decorator/Embedded'>;
}
declare module 'typeorm/decorator/error/ColumnTypeUndefinedError.js' {
  declare module.exports: $Exports<'typeorm/decorator/error/ColumnTypeUndefinedError'>;
}
declare module 'typeorm/decorator/error/GeneratedOnlyForPrimaryError.js' {
  declare module.exports: $Exports<'typeorm/decorator/error/GeneratedOnlyForPrimaryError'>;
}
declare module 'typeorm/decorator/error/PrimaryColumnCannotBeNullableError.js' {
  declare module.exports: $Exports<'typeorm/decorator/error/PrimaryColumnCannotBeNullableError'>;
}
declare module 'typeorm/decorator/Index.js' {
  declare module.exports: $Exports<'typeorm/decorator/Index'>;
}
declare module 'typeorm/decorator/listeners/AfterInsert.js' {
  declare module.exports: $Exports<'typeorm/decorator/listeners/AfterInsert'>;
}
declare module 'typeorm/decorator/listeners/AfterLoad.js' {
  declare module.exports: $Exports<'typeorm/decorator/listeners/AfterLoad'>;
}
declare module 'typeorm/decorator/listeners/AfterRemove.js' {
  declare module.exports: $Exports<'typeorm/decorator/listeners/AfterRemove'>;
}
declare module 'typeorm/decorator/listeners/AfterUpdate.js' {
  declare module.exports: $Exports<'typeorm/decorator/listeners/AfterUpdate'>;
}
declare module 'typeorm/decorator/listeners/BeforeInsert.js' {
  declare module.exports: $Exports<'typeorm/decorator/listeners/BeforeInsert'>;
}
declare module 'typeorm/decorator/listeners/BeforeRemove.js' {
  declare module.exports: $Exports<'typeorm/decorator/listeners/BeforeRemove'>;
}
declare module 'typeorm/decorator/listeners/BeforeUpdate.js' {
  declare module.exports: $Exports<'typeorm/decorator/listeners/BeforeUpdate'>;
}
declare module 'typeorm/decorator/listeners/EventSubscriber.js' {
  declare module.exports: $Exports<'typeorm/decorator/listeners/EventSubscriber'>;
}
declare module 'typeorm/decorator/NamingStrategy.js' {
  declare module.exports: $Exports<'typeorm/decorator/NamingStrategy'>;
}
declare module 'typeorm/decorator/options/ColumnOptions.js' {
  declare module.exports: $Exports<'typeorm/decorator/options/ColumnOptions'>;
}
declare module 'typeorm/decorator/options/IndexOptions.js' {
  declare module.exports: $Exports<'typeorm/decorator/options/IndexOptions'>;
}
declare module 'typeorm/decorator/options/JoinColumnOptions.js' {
  declare module.exports: $Exports<'typeorm/decorator/options/JoinColumnOptions'>;
}
declare module 'typeorm/decorator/options/JoinTableOptions.js' {
  declare module.exports: $Exports<'typeorm/decorator/options/JoinTableOptions'>;
}
declare module 'typeorm/decorator/options/RelationOptions.js' {
  declare module.exports: $Exports<'typeorm/decorator/options/RelationOptions'>;
}
declare module 'typeorm/decorator/options/TableOptions.js' {
  declare module.exports: $Exports<'typeorm/decorator/options/TableOptions'>;
}
declare module 'typeorm/decorator/relations/JoinColumn.js' {
  declare module.exports: $Exports<'typeorm/decorator/relations/JoinColumn'>;
}
declare module 'typeorm/decorator/relations/JoinTable.js' {
  declare module.exports: $Exports<'typeorm/decorator/relations/JoinTable'>;
}
declare module 'typeorm/decorator/relations/ManyToMany.js' {
  declare module.exports: $Exports<'typeorm/decorator/relations/ManyToMany'>;
}
declare module 'typeorm/decorator/relations/ManyToOne.js' {
  declare module.exports: $Exports<'typeorm/decorator/relations/ManyToOne'>;
}
declare module 'typeorm/decorator/relations/OneToMany.js' {
  declare module.exports: $Exports<'typeorm/decorator/relations/OneToMany'>;
}
declare module 'typeorm/decorator/relations/OneToOne.js' {
  declare module.exports: $Exports<'typeorm/decorator/relations/OneToOne'>;
}
declare module 'typeorm/decorator/relations/RelationCount.js' {
  declare module.exports: $Exports<'typeorm/decorator/relations/RelationCount'>;
}
declare module 'typeorm/decorator/relations/RelationId.js' {
  declare module.exports: $Exports<'typeorm/decorator/relations/RelationId'>;
}
declare module 'typeorm/decorator/tables/AbstractTable.js' {
  declare module.exports: $Exports<'typeorm/decorator/tables/AbstractTable'>;
}
declare module 'typeorm/decorator/tables/ClassTableChild.js' {
  declare module.exports: $Exports<'typeorm/decorator/tables/ClassTableChild'>;
}
declare module 'typeorm/decorator/tables/ClosureTable.js' {
  declare module.exports: $Exports<'typeorm/decorator/tables/ClosureTable'>;
}
declare module 'typeorm/decorator/tables/EmbeddableTable.js' {
  declare module.exports: $Exports<'typeorm/decorator/tables/EmbeddableTable'>;
}
declare module 'typeorm/decorator/tables/SingleTableChild.js' {
  declare module.exports: $Exports<'typeorm/decorator/tables/SingleTableChild'>;
}
declare module 'typeorm/decorator/tables/Table.js' {
  declare module.exports: $Exports<'typeorm/decorator/tables/Table'>;
}
declare module 'typeorm/decorator/tables/TableInheritance.js' {
  declare module.exports: $Exports<'typeorm/decorator/tables/TableInheritance'>;
}
declare module 'typeorm/decorator/tree/TreeChildren.js' {
  declare module.exports: $Exports<'typeorm/decorator/tree/TreeChildren'>;
}
declare module 'typeorm/decorator/tree/TreeLevelColumn.js' {
  declare module.exports: $Exports<'typeorm/decorator/tree/TreeLevelColumn'>;
}
declare module 'typeorm/decorator/tree/TreeParent.js' {
  declare module.exports: $Exports<'typeorm/decorator/tree/TreeParent'>;
}
declare module 'typeorm/decorators-shim.js' {
  declare module.exports: $Exports<'typeorm/decorators-shim'>;
}
declare module 'typeorm/driver/DatabaseConnection.js' {
  declare module.exports: $Exports<'typeorm/driver/DatabaseConnection'>;
}
declare module 'typeorm/driver/Driver.js' {
  declare module.exports: $Exports<'typeorm/driver/Driver'>;
}
declare module 'typeorm/driver/DriverOptions.js' {
  declare module.exports: $Exports<'typeorm/driver/DriverOptions'>;
}
declare module 'typeorm/driver/DriverUtils.js' {
  declare module.exports: $Exports<'typeorm/driver/DriverUtils'>;
}
declare module 'typeorm/driver/error/ConnectionIsNotSetError.js' {
  declare module.exports: $Exports<'typeorm/driver/error/ConnectionIsNotSetError'>;
}
declare module 'typeorm/driver/error/DataTypeNotSupportedByDriverError.js' {
  declare module.exports: $Exports<'typeorm/driver/error/DataTypeNotSupportedByDriverError'>;
}
declare module 'typeorm/driver/error/DriverOptionNotSetError.js' {
  declare module.exports: $Exports<'typeorm/driver/error/DriverOptionNotSetError'>;
}
declare module 'typeorm/driver/error/DriverPackageLoadError.js' {
  declare module.exports: $Exports<'typeorm/driver/error/DriverPackageLoadError'>;
}
declare module 'typeorm/driver/error/DriverPackageNotInstalledError.js' {
  declare module.exports: $Exports<'typeorm/driver/error/DriverPackageNotInstalledError'>;
}
declare module 'typeorm/driver/error/DriverPoolingNotSupportedError.js' {
  declare module.exports: $Exports<'typeorm/driver/error/DriverPoolingNotSupportedError'>;
}
declare module 'typeorm/driver/error/TransactionAlreadyStartedError.js' {
  declare module.exports: $Exports<'typeorm/driver/error/TransactionAlreadyStartedError'>;
}
declare module 'typeorm/driver/error/TransactionNotStartedError.js' {
  declare module.exports: $Exports<'typeorm/driver/error/TransactionNotStartedError'>;
}
declare module 'typeorm/driver/mysql/MysqlDriver.js' {
  declare module.exports: $Exports<'typeorm/driver/mysql/MysqlDriver'>;
}
declare module 'typeorm/driver/mysql/MysqlQueryRunner.js' {
  declare module.exports: $Exports<'typeorm/driver/mysql/MysqlQueryRunner'>;
}
declare module 'typeorm/driver/oracle/OracleDriver.js' {
  declare module.exports: $Exports<'typeorm/driver/oracle/OracleDriver'>;
}
declare module 'typeorm/driver/oracle/OracleQueryRunner.js' {
  declare module.exports: $Exports<'typeorm/driver/oracle/OracleQueryRunner'>;
}
declare module 'typeorm/driver/postgres/PostgresDriver.js' {
  declare module.exports: $Exports<'typeorm/driver/postgres/PostgresDriver'>;
}
declare module 'typeorm/driver/postgres/PostgresQueryRunner.js' {
  declare module.exports: $Exports<'typeorm/driver/postgres/PostgresQueryRunner'>;
}
declare module 'typeorm/driver/sqlite/SqliteDriver.js' {
  declare module.exports: $Exports<'typeorm/driver/sqlite/SqliteDriver'>;
}
declare module 'typeorm/driver/sqlite/SqliteQueryRunner.js' {
  declare module.exports: $Exports<'typeorm/driver/sqlite/SqliteQueryRunner'>;
}
declare module 'typeorm/driver/sqlserver/SqlServerDriver.js' {
  declare module.exports: $Exports<'typeorm/driver/sqlserver/SqlServerDriver'>;
}
declare module 'typeorm/driver/sqlserver/SqlServerQueryRunner.js' {
  declare module.exports: $Exports<'typeorm/driver/sqlserver/SqlServerQueryRunner'>;
}
declare module 'typeorm/driver/websql/WebsqlDriver.js' {
  declare module.exports: $Exports<'typeorm/driver/websql/WebsqlDriver'>;
}
declare module 'typeorm/driver/websql/WebsqlQueryRunner.js' {
  declare module.exports: $Exports<'typeorm/driver/websql/WebsqlQueryRunner'>;
}
declare module 'typeorm/entity-manager/BaseEntityManager.js' {
  declare module.exports: $Exports<'typeorm/entity-manager/BaseEntityManager'>;
}
declare module 'typeorm/entity-manager/EntityManager.js' {
  declare module.exports: $Exports<'typeorm/entity-manager/EntityManager'>;
}
declare module 'typeorm/entity-manager/error/NoNeedToReleaseEntityManagerError.js' {
  declare module.exports: $Exports<'typeorm/entity-manager/error/NoNeedToReleaseEntityManagerError'>;
}
declare module 'typeorm/entity-schema/EntitySchema.js' {
  declare module.exports: $Exports<'typeorm/entity-schema/EntitySchema'>;
}
declare module 'typeorm/find-options/FindOptions.js' {
  declare module.exports: $Exports<'typeorm/find-options/FindOptions'>;
}
declare module 'typeorm/find-options/FindOptionsUtils.js' {
  declare module.exports: $Exports<'typeorm/find-options/FindOptionsUtils'>;
}
declare module 'typeorm/find-options/OrderByCondition.js' {
  declare module.exports: $Exports<'typeorm/find-options/OrderByCondition'>;
}
declare module 'typeorm/index' {
  declare module.exports: $Exports<'typeorm'>;
}
declare module 'typeorm/index.js' {
  declare module.exports: $Exports<'typeorm'>;
}
declare module 'typeorm/lazy-loading/LazyRelationsWrapper.js' {
  declare module.exports: $Exports<'typeorm/lazy-loading/LazyRelationsWrapper'>;
}
declare module 'typeorm/logger/Logger.js' {
  declare module.exports: $Exports<'typeorm/logger/Logger'>;
}
declare module 'typeorm/logger/LoggerOptions.js' {
  declare module.exports: $Exports<'typeorm/logger/LoggerOptions'>;
}
declare module 'typeorm/metadata-args/collection/PropertyMetadataArgsCollection.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/collection/PropertyMetadataArgsCollection'>;
}
declare module 'typeorm/metadata-args/collection/TargetMetadataArgsCollection.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/collection/TargetMetadataArgsCollection'>;
}
declare module 'typeorm/metadata-args/ColumnMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/ColumnMetadataArgs'>;
}
declare module 'typeorm/metadata-args/DiscriminatorValueMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/DiscriminatorValueMetadataArgs'>;
}
declare module 'typeorm/metadata-args/EmbeddedMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/EmbeddedMetadataArgs'>;
}
declare module 'typeorm/metadata-args/EntityListenerMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/EntityListenerMetadataArgs'>;
}
declare module 'typeorm/metadata-args/EntityMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/EntityMetadataArgs'>;
}
declare module 'typeorm/metadata-args/EntitySubscriberMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/EntitySubscriberMetadataArgs'>;
}
declare module 'typeorm/metadata-args/error/EntityMetadataNotFound.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/error/EntityMetadataNotFound'>;
}
declare module 'typeorm/metadata-args/IndexMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/IndexMetadataArgs'>;
}
declare module 'typeorm/metadata-args/InheritanceMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/InheritanceMetadataArgs'>;
}
declare module 'typeorm/metadata-args/JoinColumnMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/JoinColumnMetadataArgs'>;
}
declare module 'typeorm/metadata-args/JoinTableMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/JoinTableMetadataArgs'>;
}
declare module 'typeorm/metadata-args/MetadataArgsStorage.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/MetadataArgsStorage'>;
}
declare module 'typeorm/metadata-args/NamingStrategyMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/NamingStrategyMetadataArgs'>;
}
declare module 'typeorm/metadata-args/RelationCountMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/RelationCountMetadataArgs'>;
}
declare module 'typeorm/metadata-args/RelationIdMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/RelationIdMetadataArgs'>;
}
declare module 'typeorm/metadata-args/RelationMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/RelationMetadataArgs'>;
}
declare module 'typeorm/metadata-args/TableMetadataArgs.js' {
  declare module.exports: $Exports<'typeorm/metadata-args/TableMetadataArgs'>;
}
declare module 'typeorm/metadata-builder/ClosureJunctionEntityMetadataBuilder.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/ClosureJunctionEntityMetadataBuilder'>;
}
declare module 'typeorm/metadata-builder/EntityMetadataBuilder.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/EntityMetadataBuilder'>;
}
declare module 'typeorm/metadata-builder/EntityMetadataValidator.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/EntityMetadataValidator'>;
}
declare module 'typeorm/metadata-builder/error/CircularRelationsError.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/error/CircularRelationsError'>;
}
declare module 'typeorm/metadata-builder/error/MetadataAlreadyExistsError.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/error/MetadataAlreadyExistsError'>;
}
declare module 'typeorm/metadata-builder/error/MetadataWithSuchNameAlreadyExistsError.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/error/MetadataWithSuchNameAlreadyExistsError'>;
}
declare module 'typeorm/metadata-builder/error/MissingJoinColumnError.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/error/MissingJoinColumnError'>;
}
declare module 'typeorm/metadata-builder/error/MissingJoinTableError.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/error/MissingJoinTableError'>;
}
declare module 'typeorm/metadata-builder/error/MissingPrimaryColumnError.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/error/MissingPrimaryColumnError'>;
}
declare module 'typeorm/metadata-builder/error/UsingJoinColumnIsNotAllowedError.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/error/UsingJoinColumnIsNotAllowedError'>;
}
declare module 'typeorm/metadata-builder/error/UsingJoinColumnOnlyOnOneSideAllowedError.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/error/UsingJoinColumnOnlyOnOneSideAllowedError'>;
}
declare module 'typeorm/metadata-builder/error/UsingJoinTableIsNotAllowedError.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/error/UsingJoinTableIsNotAllowedError'>;
}
declare module 'typeorm/metadata-builder/error/UsingJoinTableOnlyOnOneSideAllowedError.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/error/UsingJoinTableOnlyOnOneSideAllowedError'>;
}
declare module 'typeorm/metadata-builder/JunctionEntityMetadataBuilder.js' {
  declare module.exports: $Exports<'typeorm/metadata-builder/JunctionEntityMetadataBuilder'>;
}
declare module 'typeorm/metadata/ColumnMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/ColumnMetadata'>;
}
declare module 'typeorm/metadata/EmbeddedMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/EmbeddedMetadata'>;
}
declare module 'typeorm/metadata/EntityListenerMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/EntityListenerMetadata'>;
}
declare module 'typeorm/metadata/EntityMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/EntityMetadata'>;
}
declare module 'typeorm/metadata/EntitySubscriberMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/EntitySubscriberMetadata'>;
}
declare module 'typeorm/metadata/error/EntityMetadataAlreadySetError.js' {
  declare module.exports: $Exports<'typeorm/metadata/error/EntityMetadataAlreadySetError'>;
}
declare module 'typeorm/metadata/error/EntityMetadataNotSetError.js' {
  declare module.exports: $Exports<'typeorm/metadata/error/EntityMetadataNotSetError'>;
}
declare module 'typeorm/metadata/ForeignKeyMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/ForeignKeyMetadata'>;
}
declare module 'typeorm/metadata/IndexMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/IndexMetadata'>;
}
declare module 'typeorm/metadata/JoinColumnMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/JoinColumnMetadata'>;
}
declare module 'typeorm/metadata/JoinTableMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/JoinTableMetadata'>;
}
declare module 'typeorm/metadata/PropertyMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/PropertyMetadata'>;
}
declare module 'typeorm/metadata/RelationCountMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/RelationCountMetadata'>;
}
declare module 'typeorm/metadata/RelationMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/RelationMetadata'>;
}
declare module 'typeorm/metadata/TableMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/TableMetadata'>;
}
declare module 'typeorm/metadata/TargetMetadata.js' {
  declare module.exports: $Exports<'typeorm/metadata/TargetMetadata'>;
}
declare module 'typeorm/metadata/types/ColumnTypes.js' {
  declare module.exports: $Exports<'typeorm/metadata/types/ColumnTypes'>;
}
declare module 'typeorm/metadata/types/EventListenerTypes.js' {
  declare module.exports: $Exports<'typeorm/metadata/types/EventListenerTypes'>;
}
declare module 'typeorm/metadata/types/RelationTypes.js' {
  declare module.exports: $Exports<'typeorm/metadata/types/RelationTypes'>;
}
declare module 'typeorm/metadata/types/TableTypes.js' {
  declare module.exports: $Exports<'typeorm/metadata/types/TableTypes'>;
}
declare module 'typeorm/migration/Migration.js' {
  declare module.exports: $Exports<'typeorm/migration/Migration'>;
}
declare module 'typeorm/migration/MigrationExecutor.js' {
  declare module.exports: $Exports<'typeorm/migration/MigrationExecutor'>;
}
declare module 'typeorm/migration/MigrationInterface.js' {
  declare module.exports: $Exports<'typeorm/migration/MigrationInterface'>;
}
declare module 'typeorm/naming-strategy/DefaultNamingStrategy.js' {
  declare module.exports: $Exports<'typeorm/naming-strategy/DefaultNamingStrategy'>;
}
declare module 'typeorm/naming-strategy/NamingStrategyInterface.js' {
  declare module.exports: $Exports<'typeorm/naming-strategy/NamingStrategyInterface'>;
}
declare module 'typeorm/persistence/error/CascadesNotAllowedError.js' {
  declare module.exports: $Exports<'typeorm/persistence/error/CascadesNotAllowedError'>;
}
declare module 'typeorm/persistence/error/PersistedEntityNotFoundError.js' {
  declare module.exports: $Exports<'typeorm/persistence/error/PersistedEntityNotFoundError'>;
}
declare module 'typeorm/persistence/Subject.js' {
  declare module.exports: $Exports<'typeorm/persistence/Subject'>;
}
declare module 'typeorm/persistence/SubjectBuilder.js' {
  declare module.exports: $Exports<'typeorm/persistence/SubjectBuilder'>;
}
declare module 'typeorm/persistence/SubjectOperationExecutor.js' {
  declare module.exports: $Exports<'typeorm/persistence/SubjectOperationExecutor'>;
}
declare module 'typeorm/platform/PlatformTools.js' {
  declare module.exports: $Exports<'typeorm/platform/PlatformTools'>;
}
declare module 'typeorm/query-builder/alias/Alias.js' {
  declare module.exports: $Exports<'typeorm/query-builder/alias/Alias'>;
}
declare module 'typeorm/query-builder/alias/AliasMap.js' {
  declare module.exports: $Exports<'typeorm/query-builder/alias/AliasMap'>;
}
declare module 'typeorm/query-builder/JoinOptions.js' {
  declare module.exports: $Exports<'typeorm/query-builder/JoinOptions'>;
}
declare module 'typeorm/query-builder/QueryBuilder.js' {
  declare module.exports: $Exports<'typeorm/query-builder/QueryBuilder'>;
}
declare module 'typeorm/query-builder/transformer/PlainObjectToDatabaseEntityTransformer.js' {
  declare module.exports: $Exports<'typeorm/query-builder/transformer/PlainObjectToDatabaseEntityTransformer'>;
}
declare module 'typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer.js' {
  declare module.exports: $Exports<'typeorm/query-builder/transformer/PlainObjectToNewEntityTransformer'>;
}
declare module 'typeorm/query-builder/transformer/RawSqlResultsToEntityTransformer.js' {
  declare module.exports: $Exports<'typeorm/query-builder/transformer/RawSqlResultsToEntityTransformer'>;
}
declare module 'typeorm/query-runner/error/QueryRunnerAlreadyReleasedError.js' {
  declare module.exports: $Exports<'typeorm/query-runner/error/QueryRunnerAlreadyReleasedError'>;
}
declare module 'typeorm/query-runner/error/QueryRunnerProviderAlreadyReleasedError.js' {
  declare module.exports: $Exports<'typeorm/query-runner/error/QueryRunnerProviderAlreadyReleasedError'>;
}
declare module 'typeorm/query-runner/QueryRunner.js' {
  declare module.exports: $Exports<'typeorm/query-runner/QueryRunner'>;
}
declare module 'typeorm/query-runner/QueryRunnerProvider.js' {
  declare module.exports: $Exports<'typeorm/query-runner/QueryRunnerProvider'>;
}
declare module 'typeorm/repository/Repository.js' {
  declare module.exports: $Exports<'typeorm/repository/Repository'>;
}
declare module 'typeorm/repository/RepositoryAggregator.js' {
  declare module.exports: $Exports<'typeorm/repository/RepositoryAggregator'>;
}
declare module 'typeorm/repository/RepositoryFactory.js' {
  declare module.exports: $Exports<'typeorm/repository/RepositoryFactory'>;
}
declare module 'typeorm/repository/SpecificRepository.js' {
  declare module.exports: $Exports<'typeorm/repository/SpecificRepository'>;
}
declare module 'typeorm/repository/TreeRepository.js' {
  declare module.exports: $Exports<'typeorm/repository/TreeRepository'>;
}
declare module 'typeorm/schema-builder/schema/ColumnSchema.js' {
  declare module.exports: $Exports<'typeorm/schema-builder/schema/ColumnSchema'>;
}
declare module 'typeorm/schema-builder/schema/ForeignKeySchema.js' {
  declare module.exports: $Exports<'typeorm/schema-builder/schema/ForeignKeySchema'>;
}
declare module 'typeorm/schema-builder/schema/IndexSchema.js' {
  declare module.exports: $Exports<'typeorm/schema-builder/schema/IndexSchema'>;
}
declare module 'typeorm/schema-builder/schema/PrimaryKeySchema.js' {
  declare module.exports: $Exports<'typeorm/schema-builder/schema/PrimaryKeySchema'>;
}
declare module 'typeorm/schema-builder/schema/TableSchema.js' {
  declare module.exports: $Exports<'typeorm/schema-builder/schema/TableSchema'>;
}
declare module 'typeorm/schema-builder/SchemaBuilder.js' {
  declare module.exports: $Exports<'typeorm/schema-builder/SchemaBuilder'>;
}
declare module 'typeorm/subscriber/Broadcaster.js' {
  declare module.exports: $Exports<'typeorm/subscriber/Broadcaster'>;
}
declare module 'typeorm/subscriber/EntitySubscriberInterface.js' {
  declare module.exports: $Exports<'typeorm/subscriber/EntitySubscriberInterface'>;
}
declare module 'typeorm/subscriber/event/InsertEvent.js' {
  declare module.exports: $Exports<'typeorm/subscriber/event/InsertEvent'>;
}
declare module 'typeorm/subscriber/event/RemoveEvent.js' {
  declare module.exports: $Exports<'typeorm/subscriber/event/RemoveEvent'>;
}
declare module 'typeorm/subscriber/event/UpdateEvent.js' {
  declare module.exports: $Exports<'typeorm/subscriber/event/UpdateEvent'>;
}
declare module 'typeorm/util/DataTransformationUtils.js' {
  declare module.exports: $Exports<'typeorm/util/DataTransformationUtils'>;
}
declare module 'typeorm/util/DepGraph.js' {
  declare module.exports: $Exports<'typeorm/util/DepGraph'>;
}
declare module 'typeorm/util/DirectoryExportedClassesLoader.js' {
  declare module.exports: $Exports<'typeorm/util/DirectoryExportedClassesLoader'>;
}
declare module 'typeorm/util/OrmUtils.js' {
  declare module.exports: $Exports<'typeorm/util/OrmUtils'>;
}
declare module 'typeorm/util/PromiseUtils.js' {
  declare module.exports: $Exports<'typeorm/util/PromiseUtils'>;
}
declare module 'typeorm/util/RandomGenerator.js' {
  declare module.exports: $Exports<'typeorm/util/RandomGenerator'>;
}
declare module 'typeorm/util/StringUtils.js' {
  declare module.exports: $Exports<'typeorm/util/StringUtils'>;
}
